name: Docker CI Build & Push

on:   
  push:
    branches:
      - master

jobs:
  build_push_docker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Docker Login
      env: 
        DOCKER_USER: ${{ secrets.DOCKER_USER }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD

    - name: Docker build
      run: |
        docker build ./ -t gaxze/node-web-app:latest
    
    - name: Docker push
      run: |
        docker push gaxze/node-web-app:latest
